service: MusicAroundMe

provider:
    name: aws
    stage: PROD
    memorySize: 3008
    timeout: 30
    runtime: nodejs8.10
    region: ap-southeast-2
    apiKeys:
        - MUSIC_AROUND_ME_API_KEY

functions:
    getEvents:
        handler: getEvents/handler.getEvents
        environment:
            API_KEY: jhDKbPlJL4AVGmUTxxA7701jnK2vcOEu
        events:
            - http:
                  path: getEvents
                  method: get
                  private: true
                  cors:
                      origin: '*'
