service: MusicAroundMe
package:
    excludeDevDependencies: true

provider:
    name: aws
    stage: PROD
    memorySize: 3008
    timeout: 30
    runtime: nodejs8.10
    region: ap-southeast-2
    apiKeys:
        - MUSIC_AROUND_ME_API_KEY
    iamRoleStatements:
        - Effect: Allow
          Action:
              - 'dynamodb:*'
          Resource: '*'

functions:
    getEvents:
        handler: getEvents/handler.getEvents
        environment:
            TICKETMASTER_API_KEY: jhDKbPlJL4AVGmUTxxA7701jnK2vcOEu
            SONGKICK_API_KEY: jjTwg0sS5Y4glVjE
        events:
            - http:
                  path: events/event
                  method: get
                  request:
                      parameters:
                          paths:
                              jobId: true
                  private: true
                  cors:
                      origin: '*'
    getClassifications:
        handler: getClassifications/handler.getClassifications
        environment:
            TICKETMASTER_API_KEY: jhDKbPlJL4AVGmUTxxA7701jnK2vcOEu
        events:
            - http:
                  path: classifications
                  method: get
                  private: true
                  cors:
                      origin: '*'
    getConfiguration:
        handler: getConfiguration/handler.getConfiguration
        events:
            - http:
                  path: configuration
                  method: get
                  cors:
                      origin: '*'
