pipelines:
    branches:
        'master':
            - step:
                  name: Build
                  image: node:alpine
                  caches:
                      - node
                  script:
                      - yarn
                      - yarn build
                  artifacts:
                      - dist/**
            - step:
                  name: Deploy
                  image: atlassian/pipelines-awscli
                  script:
                      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                      - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
                      - aws s3 sync dist s3://musicaroundme.io
