image: node:10
pipelines:
    branches:
        'master':
            - step:
                  name: Build
                  image: atlassian/pipelines-awscli
                  script:
                      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
                      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
                      - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
                      - npm run build
                      - aws s3 sync dist/ s3://musicaroundme
