image: node:alpine
pipelines:
    default:
        - step:
              script:
                  - yarn
    branches:
        'master':
            - step:
                  name: Build
                  image: atlassian/pipelines-awscli
                  services:
                      - docker
                  script:
                      - export AWS_ACCESS_KEY_ID=AKIAISZEF54RU6IHSDMA
                      - export AWS_SECRET_ACCESS_KEY=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
                      - export AWS_DEFAULT_REGION=ap-southeast-2
                      - yarn build
                      - aws s3 sync dist/ s3://musicaroundme
definitions:
    services:
        docker:
            memory: 1024
